apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp1
  name: webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp1
    spec:
      containers:
      - image: dockerashu/lnbweb:v1
        name: v1
        imagePullPolicy: Always
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc1
  name: svc1
spec:
  ports:
  - name: 1234-8080
    port: 1234
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp1
  type: NodePort
status:
  loadBalancer: {}

        
       
